-- MySQL Script generated by MySQL Workbench
-- 05/14/16 14:38:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesor` (
  `id_profesora` INT NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  PRIMARY KEY (`id_profesora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Katedra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Katedra` (
  `godina_studija` INT NOT NULL,
  `Profesor_id_profesora` INT NOT NULL,
  `godina_konfiguracije` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`godina_studija`, `Profesor_id_profesora`, `godina_konfiguracije`),
  INDEX `fk_Katedra_Profesor1_idx` (`Profesor_id_profesora` ASC),
  CONSTRAINT `fk_Katedra_Profesor1`
    FOREIGN KEY (`Profesor_id_profesora`)
    REFERENCES `mydb`.`Profesor` (`id_profesora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vezba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vezba` (
  `id_vezbe` VARCHAR(45) NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `opis` LONGTEXT NULL,
  `tip` VARCHAR(45) NULL,
  PRIMARY KEY (`id_vezbe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Film` (
  `id_filma` INT NOT NULL,
  `godina_proizvodnje` INT NULL,
  `naziv_filma` VARCHAR(45) NULL,
  `trajanje` INT NULL,
  `Katedra_godina_studija` INT NOT NULL,
  `Katedra_Profesor_id_profesora` INT NOT NULL,
  `Katedra_godina_konfiguracije` INT NOT NULL,
  `Vezba_id_vezbe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_filma`, `Katedra_godina_studija`, `Katedra_Profesor_id_profesora`, `Katedra_godina_konfiguracije`, `Vezba_id_vezbe`),
  INDEX `fk_Film_Katedra1_idx` (`Katedra_godina_studija` ASC, `Katedra_Profesor_id_profesora` ASC, `Katedra_godina_konfiguracije` ASC),
  INDEX `fk_Film_Vezba1_idx` (`Vezba_id_vezbe` ASC),
  CONSTRAINT `fk_Film_Katedra1`
    FOREIGN KEY (`Katedra_godina_studija` , `Katedra_Profesor_id_profesora` , `Katedra_godina_konfiguracije`)
    REFERENCES `mydb`.`Katedra` (`godina_studija` , `Profesor_id_profesora` , `godina_konfiguracije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_Vezba1`
    FOREIGN KEY (`Vezba_id_vezbe`)
    REFERENCES `mydb`.`Vezba` (`id_vezbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `id_studenta` INT NOT NULL,
  `indeks` MEDIUMTEXT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  `godina_studija` INT NULL,
  `naziv_katedre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_studenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Snimatelj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Snimatelj` (
  `Film_id_filma` INT NOT NULL,
  `Student_id_studenta` INT NOT NULL,
  PRIMARY KEY (`Film_id_filma`, `Student_id_studenta`),
  INDEX `fk_Film_has_Student_Student1_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Film_has_Student_Film1_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Student_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`Student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reziser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reziser` (
  `Film_id_filma` INT NOT NULL,
  `Student_id_studenta` INT NOT NULL,
  PRIMARY KEY (`Film_id_filma`, `Student_id_studenta`),
  INDEX `fk_Film_has_Student_Student2_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Film_has_Student_Film2_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film2`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Student_Student2`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`Student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producent` (
  `Film_id_filma` INT NOT NULL,
  `Student_id_studenta` INT NOT NULL,
  PRIMARY KEY (`Film_id_filma`, `Student_id_studenta`),
  INDEX `fk_Film_has_Student_Student3_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Film_has_Student_Film3_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film3`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Student_Student3`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`Student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Montazer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Montazer` (
  `Film_id_filma` INT NOT NULL,
  `Student_id_studenta` INT NOT NULL,
  PRIMARY KEY (`Film_id_filma`, `Student_id_studenta`),
  INDEX `fk_Film_has_Student_Student4_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Film_has_Student_Film4_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film4`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Student_Student4`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`Student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glumac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glumac` (
  `Film_id_filma` INT NOT NULL,
  `Student_id_studenta` INT NOT NULL,
  PRIMARY KEY (`Film_id_filma`, `Student_id_studenta`),
  INDEX `fk_Film_has_Student_Student5_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Film_has_Student_Film5_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film5`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Student_Student5`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`Student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Info_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Info_film` (
  `Film_id_filma` INT NOT NULL,
  `tip_info` VARCHAR(45) NOT NULL,
  `sadrzaj_info` LONGTEXT NULL,
  PRIMARY KEY (`Film_id_filma`, `tip_info`),
  INDEX `fk_Info_film_Film1_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Info_film_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tehnicka_specifikacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tehnicka_specifikacija` (
  `Film_id_filma` INT NOT NULL,
  `osnovni_format` VARCHAR(45) NULL,
  `filmski_format` VARCHAR(45) NULL,
  `video_format` VARCHAR(45) NULL,
  `tel_standard` VARCHAR(45) NULL,
  `analiza_slike` VARCHAR(45) NULL,
  `format_slike` VARCHAR(45) NULL,
  `br_sl_sek` VARCHAR(45) NULL,
  `video_nosac` VARCHAR(45) NULL,
  `vrsta_fajla` VARCHAR(45) NULL,
  `zvuk` VARCHAR(45) NULL,
  `broj_kanala` VARCHAR(45) NULL,
  `redukcija_suma` VARCHAR(45) NULL,
  `varijacije_zvuka` VARCHAR(45) NULL,
  `napomene` LONGTEXT NULL,
  INDEX `fk_Tehnicka_specifikacija_Film1_idx` (`Film_id_filma` ASC),
  PRIMARY KEY (`Film_id_filma`),
  CONSTRAINT `fk_Tehnicka_specifikacija_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Podrska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Podrska` (
  `Film_id_filma` INT NOT NULL,
  `tip_podrske` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  PRIMARY KEY (`Film_id_filma`, `tip_podrske`),
  CONSTRAINT `fk_Podrska_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Karton_prilog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Karton_prilog` (
  `Film_id_filma` INT NOT NULL,
  `tip_priloga` VARCHAR(45) NOT NULL,
  `putanja` VARCHAR(300) NULL,
  PRIMARY KEY (`Film_id_filma`, `tip_priloga`),
  CONSTRAINT `fk_Karton_prilog_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`Film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vezba_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vezba_student` (
  `Vezba_id_vezbe` VARCHAR(45) NOT NULL,
  `Student_id_studenta` INT NOT NULL,
  PRIMARY KEY (`Vezba_id_vezbe`, `Student_id_studenta`),
  INDEX `fk_Vezba_has_Student_Student1_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Vezba_has_Student_Vezba1_idx` (`Vezba_id_vezbe` ASC),
  CONSTRAINT `fk_Vezba_has_Student_Vezba1`
    FOREIGN KEY (`Vezba_id_vezbe`)
    REFERENCES `mydb`.`Vezba` (`id_vezbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vezba_has_Student_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`Student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vezba_profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vezba_profesor` (
  `Vezba_id_vezbe` VARCHAR(45) NOT NULL,
  `Profesor_id_profesora` INT NOT NULL,
  PRIMARY KEY (`Vezba_id_vezbe`, `Profesor_id_profesora`),
  INDEX `fk_Vezba_has_Profesor_Profesor1_idx` (`Profesor_id_profesora` ASC),
  INDEX `fk_Vezba_has_Profesor_Vezba1_idx` (`Vezba_id_vezbe` ASC),
  CONSTRAINT `fk_Vezba_has_Profesor_Vezba1`
    FOREIGN KEY (`Vezba_id_vezbe`)
    REFERENCES `mydb`.`Vezba` (`id_vezbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vezba_has_Profesor_Profesor1`
    FOREIGN KEY (`Profesor_id_profesora`)
    REFERENCES `mydb`.`Profesor` (`id_profesora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrator` (
  `sifra` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  `napomene` VARCHAR(45) NULL,
  PRIMARY KEY (`sifra`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
