-- MySQL Script generated by MySQL Workbench
-- 06/13/16 02:27:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrator` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`predmet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`predmet` (
  `id_predmeta` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_predmeta`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`vezba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vezba` (
  `id_vezbe` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NULL DEFAULT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `tip` VARCHAR(255) NULL DEFAULT NULL,
  `Predmet_id_predmeta` INT(11) NOT NULL,
  PRIMARY KEY (`id_vezbe`),
  INDEX `fk_Vezba_Predmet1_idx` (`Predmet_id_predmeta` ASC),
  CONSTRAINT `fk_Vezba_Predmet1`
    FOREIGN KEY (`Predmet_id_predmeta`)
    REFERENCES `mydb`.`predmet` (`id_predmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film` (
  `id_filma` INT(11) NOT NULL AUTO_INCREMENT,
  `Vezba_id_vezbe` INT(11) NOT NULL,
  `godina_proizvodnje` INT(11) NULL DEFAULT NULL,
  `naziv_filma` VARCHAR(255) NULL DEFAULT NULL,
  `trajanje` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_filma`),
  INDEX `fk_Film_Vezba1_idx` (`Vezba_id_vezbe` ASC),
  CONSTRAINT `fk_Film_Vezba1`
    FOREIGN KEY (`Vezba_id_vezbe`)
    REFERENCES `mydb`.`vezba` (`id_vezbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 159
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`glumac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glumac` (
  `id_glumca` INT(11) NOT NULL AUTO_INCREMENT,
  `Film_id_filma` INT(11) NOT NULL,
  `ime_prezime` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_glumca`),
  INDEX `fk_Film_has_Student_Film5_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film5`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id_studenta` INT(11) NOT NULL AUTO_INCREMENT,
  `indeks` MEDIUMTEXT NULL DEFAULT NULL,
  `ime_prezime` VARCHAR(255) NULL DEFAULT NULL,
  `e_mail` VARCHAR(255) NULL DEFAULT NULL,
  `godina_studija` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_studenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`glumac_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glumac_student` (
  `Film_id_filma` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  PRIMARY KEY (`Film_id_filma`, `Student_id_studenta`),
  INDEX `fk_Film_has_Student_Student1_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Film_has_Student_Film6_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film6`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Student_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`karton_prilog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`karton_prilog` (
  `id_priloga` INT(11) NOT NULL AUTO_INCREMENT,
  `Film_id_filma` INT(11) NOT NULL,
  `tip_priloga` VARCHAR(255) NOT NULL,
  `putanja` VARCHAR(600) NULL DEFAULT NULL,
  PRIMARY KEY (`id_priloga`),
  INDEX `fk_Karton_prilog_Film1` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Karton_prilog_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `id_profesora` INT(11) NOT NULL AUTO_INCREMENT,
  `ime_prezime` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_profesora`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`katedra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`katedra` (
  `id_katedre` INT NOT NULL AUTO_INCREMENT,
  `godina_studija` INT(11) NOT NULL,
  `skolska_godina` INT(11) NOT NULL,
  `naziv` VARCHAR(255) NOT NULL,
  `Profesor_id_profesora` INT(11) NOT NULL,
  PRIMARY KEY (`id_katedre`),
  INDEX `fk_Katedra_Profesor1_idx` (`Profesor_id_profesora` ASC),
  CONSTRAINT `fk_Katedra_Profesor1`
    FOREIGN KEY (`Profesor_id_profesora`)
    REFERENCES `mydb`.`profesor` (`id_profesora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`montazer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`montazer` (
  `Film_id_filma` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  INDEX `fk_Film_has_Student_Film4_idx` (`Film_id_filma` ASC),
  INDEX `fk_Montazer_Student1_idx` (`Student_id_studenta` ASC),
  CONSTRAINT `fk_Film_has_Student_Film4`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Montazer_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`nagrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nagrada` (
  `id_nagrade` INT(11) NOT NULL AUTO_INCREMENT,
  `Film_id_filma` INT(11) NOT NULL,
  `naziv` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_nagrade`),
  INDEX `fk_Nagrada_Film1_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Nagrada_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`osnovne_informacije`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`osnovne_informacije` (
  `Film_id_filma` INT(11) NOT NULL,
  `sinopsis` TEXT NULL DEFAULT NULL,
  `arhivska_muzika` TEXT NULL DEFAULT NULL,
  `biografija_rezisera` TEXT NULL DEFAULT NULL,
  `napomene` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Film_id_filma`),
  INDEX `fk_Info_film_Film1_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Info_film_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`podrska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`podrska` (
  `id_podrske` INT(11) NOT NULL AUTO_INCREMENT,
  `Film_id_filma` INT(11) NOT NULL,
  `tip_podrske` VARCHAR(255) NULL DEFAULT NULL,
  `ime_prezime` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_podrske`),
  INDEX `fk_Podrska_Film1` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Podrska_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`podrska_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`podrska_student` (
  `Film_id_filma` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  `tip_podrske` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Student_id_studenta`, `Film_id_filma`, `tip_podrske`),
  INDEX `fk_Film_has_Student_Student2_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Film_has_Student_Film7_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Film_has_Student_Film7`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Student_Student2`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`producent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producent` (
  `Film_id_filma` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  INDEX `fk_Film_has_Student_Film3_idx` (`Film_id_filma` ASC),
  INDEX `fk_Producent_Student1_idx` (`Student_id_studenta` ASC),
  CONSTRAINT `fk_Film_has_Student_Film3`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producent_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reziser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reziser` (
  `Film_id_filma` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  INDEX `fk_Film_has_Student_Film2_idx` (`Film_id_filma` ASC),
  INDEX `fk_Reziser_Student1_idx` (`Student_id_studenta` ASC),
  CONSTRAINT `fk_Film_has_Student_Film2`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reziser_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`scenarista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`scenarista` (
  `Film_id_filma` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  INDEX `fk_Film_has_Student_Film1_idx` (`Film_id_filma` ASC),
  INDEX `fk_Snimatelj_Student1_idx` (`Student_id_studenta` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`snimatelj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`snimatelj` (
  `Film_id_filma` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  INDEX `fk_Film_has_Student_Film1_idx` (`Film_id_filma` ASC),
  INDEX `fk_Snimatelj_Student1_idx` (`Student_id_studenta` ASC),
  CONSTRAINT `fk_Film_has_Student_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Snimatelj_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tehnicka_specifikacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tehnicka_specifikacija` (
  `Film_id_filma` INT(11) NOT NULL,
  `osnovni_format` VARCHAR(255) NULL DEFAULT NULL,
  `filmski_format` VARCHAR(255) NULL DEFAULT NULL,
  `video_format` VARCHAR(255) NULL DEFAULT NULL,
  `tel_standard` VARCHAR(255) NULL DEFAULT NULL,
  `analiza_slike` VARCHAR(255) NULL DEFAULT NULL,
  `format_slike` VARCHAR(255) NULL DEFAULT NULL,
  `br_sl_sek` VARCHAR(255) NULL DEFAULT NULL,
  `video_nosac` VARCHAR(255) NULL DEFAULT NULL,
  `vrsta_fajla` VARCHAR(255) NULL DEFAULT NULL,
  `zvuk` VARCHAR(255) NULL DEFAULT NULL,
  `broj_kanala` VARCHAR(255) NULL DEFAULT NULL,
  `redukcija_suma` VARCHAR(255) NULL DEFAULT NULL,
  `varijacije_zvuka` TEXT NULL DEFAULT NULL,
  `napomene` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Film_id_filma`),
  INDEX `fk_Tehnicka_specifikacija_Film1_idx` (`Film_id_filma` ASC),
  CONSTRAINT `fk_Tehnicka_specifikacija_Film1`
    FOREIGN KEY (`Film_id_filma`)
    REFERENCES `mydb`.`film` (`id_filma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`vezba_katedra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vezba_katedra` (
  `Vezba_id_vezbe` INT(11) NOT NULL,
  `Katedra_id_katedre` INT NOT NULL,
  PRIMARY KEY (`Vezba_id_vezbe`, `Katedra_id_katedre`),
  INDEX `fk_Katedra_has_Vezba_Vezba1_idx` (`Vezba_id_vezbe` ASC),
  INDEX `fk_vezba_katedra_katedra1_idx` (`Katedra_id_katedre` ASC),
  CONSTRAINT `fk_Katedra_has_Vezba_Vezba1`
    FOREIGN KEY (`Vezba_id_vezbe`)
    REFERENCES `mydb`.`vezba` (`id_vezbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vezba_katedra_katedra1`
    FOREIGN KEY (`Katedra_id_katedre`)
    REFERENCES `mydb`.`katedra` (`id_katedre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`vezba_studenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vezba_studenti` (
  `Vezba_id_vezbe` INT(11) NOT NULL,
  `Student_id_studenta` INT(11) NOT NULL,
  PRIMARY KEY (`Vezba_id_vezbe`, `Student_id_studenta`),
  INDEX `fk_Vezba_has_Student_Student1_idx` (`Student_id_studenta` ASC),
  INDEX `fk_Vezba_has_Student_Vezba1_idx` (`Vezba_id_vezbe` ASC),
  CONSTRAINT `fk_Vezba_has_Student_Student1`
    FOREIGN KEY (`Student_id_studenta`)
    REFERENCES `mydb`.`student` (`id_studenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vezba_has_Student_Vezba1`
    FOREIGN KEY (`Vezba_id_vezbe`)
    REFERENCES `mydb`.`vezba` (`id_vezbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
